[package]
name = "rusty_mockall_example"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = "0.13.0"
mockito = "1.5.0"
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
